version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven...
      - curl -sSL https://archive.apache.org/dist/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.zip -o maven.zip
      - unzip maven.zip
      - export PATH=$PATH:`pwd`/apache-maven-3.8.6/bin
      - mvn -v
  build:
    commands:
      - echo Building the project...
      - mvn clean install
artifacts:
  files:
    - target/*.jar
